apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: zipkin-gcp
  name: zipkin-gcp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: zipkin-gcp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: zipkin-gcp
    spec:
      containers:
      - image: openzipkin/zipkin-gcp
        imagePullPolicy: Always
        name: zipkin-gcp
        env:
          - name: STORAGE_TYPE
            value: stackdriver
          - name: STACKDRIVER_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: gcp
                key: project-id
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/run/secret/cloud.google.com/service-account.json
        volumeMounts:
          - name: service-account
            mountPath: /var/run/secret/cloud.google.com
        ports:
        - containerPort: 9411
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: service-account
        secret:
          secretName: gcp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: zipkin-gcp
  name: zipkin-gcp
  namespace: default
spec:
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    run: zipkin-gcp
  sessionAffinity: None
  type: LoadBalancer
